"""project stage 1

Revision ID: 0738ab8865ff
Revises: 
Create Date: 2021-11-02 22:14:29.351402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0738ab8865ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('file_date', sa.Date(), nullable=False),
    sa.Column('file_length', sa.BIGINT(), nullable=False),
    sa.Column('file_type', sa.BIGINT(), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('name', 'file_date', 'file_length', name='uf_1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
