"""project stage 11

Revision ID: 2ded2239bfb6
Revises: 
Create Date: 2021-11-05 00:22:50.157444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ded2239bfb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_and_notes_tag_id_fkey', 'tags_and_notes', type_='foreignkey')
    op.drop_constraint('tags_and_notes_note_id_fkey', 'tags_and_notes', type_='foreignkey')
    op.create_foreign_key(None, 'tags_and_notes', 'tag', ['tag_id'], ['tag_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_and_notes', 'note', ['note_id'], ['note_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_and_notes', type_='foreignkey')
    op.drop_constraint(None, 'tags_and_notes', type_='foreignkey')
    op.create_foreign_key('tags_and_notes_note_id_fkey', 'tags_and_notes', 'note', ['note_id'], ['note_id'])
    op.create_foreign_key('tags_and_notes_tag_id_fkey', 'tags_and_notes', 'tag', ['tag_id'], ['tag_id'])
    # ### end Alembic commands ###
