"""project stage 5

Revision ID: 3bff9bfdcdbf
Revises: 048006670bb3
Create Date: 2021-11-03 02:38:26.171122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bff9bfdcdbf'
down_revision = '048006670bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uf_1', 'file', type_='unique')
    op.create_unique_constraint('uf_1', 'file', ['name', 'file_date', 'file_length', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uf_1', 'file', type_='unique')
    op.create_unique_constraint('uf_1', 'file', ['name', 'file_date', 'file_length'])
    # ### end Alembic commands ###
