"""project stage 7

Revision ID: 58740fb9f2e5
Revises: 657d492a8b4c
Create Date: 2021-11-03 16:41:49.527813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58740fb9f2e5'
down_revision = '657d492a8b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    op.add_column('note', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'text')
    op.create_table('text',
    sa.Column('text_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.note_id'], name='text_note_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('text_id', name='text_pkey')
    )
    # ### end Alembic commands ###
