"""project stage 6

Revision ID: 657d492a8b4c
Revises: 3bff9bfdcdbf
Create Date: 2021-11-03 08:36:23.834779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657d492a8b4c'
down_revision = '3bff9bfdcdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uf_1', 'file', type_='unique')
    op.create_unique_constraint('uf_1', 'file', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uf_1', 'file', type_='unique')
    op.create_unique_constraint('uf_1', 'file', ['name', 'file_date', 'file_length', 'user_id'])
    # ### end Alembic commands ###
