"""project stage 3

Revision ID: a0e9584cb9f6
Revises: dc2e454805ae
Create Date: 2021-11-03 00:45:40.373279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e9584cb9f6'
down_revision = 'dc2e454805ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_type',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_type',
               existing_type=sa.String(length=20),
               type_=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
