"""project stage 9

Revision ID: c455a5e5c2bd
Revises: 73a3be186c65
Create Date: 2021-11-04 11:59:07.768084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c455a5e5c2bd'
down_revision = '73a3be186c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'user_', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    # ### end Alembic commands ###
