"""project stage 2

Revision ID: dc2e454805ae
Revises: 0738ab8865ff
Create Date: 2021-11-02 23:09:12.890340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2e454805ae'
down_revision = '0738ab8865ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
